### PR TITLE
fix(magefiles): remove "v" prefix from version

### PR DESCRIPTION
**Pull request by mariiatuzovska**

### CODE REVIEW

**Comment by sheldonhull** [comment]
Nice! Let me look into what this might impact and get back on this. That method also might end up impacting the GitHub release naming, tag naming and more. Thanks for bringing it up!

**Comment by sheldonhull** [comment]
@mariiatuzovska  what was the error message so I can double check this today? I want to see if it's possible to fix just the generate of the cli version json without touching the version function itself?

**Comment by mariiatuzovska** [comment]
> @mariiatuzovska what was the error message so I can double check this today? I want to see if it's possible to fix just the generate of the cli version json without touching the version function itself?

When you need to update a cli version it downloads file with version. This file should not have v prefix.

**Comment by sheldonhull** [comment]
> > @mariiatuzovska what was the error message so I can double check this today? I want to see if it's possible to fix just the generate of the cli version json without touching the version function itself?
> 
> When you need to update a cli version it downloads file with version. This file should not have v prefix.

Do you have the error message though or is it just not finding it? Any pointer would be great. Didn't get a chance to look today but didn't forget about this.

I'm mostly taking this one slow as it deviates from every other repo then so I want to make sure I understand and handle this correctly so it doesn't impact the tagging scheme, goreleaser, etc. I wanted to examine as we can adjust the json format, but I want to know where this problematic logic is and see how we are parsing it. I'll try and look tomorrow if you don't get time. cheers!

**Review by sheldonhull — COMMENTED** [review]
```
	newJSON := cliVersions{
		Latest: strings.TrimPrefix(releaseVersion, "v"),

```

So that's what I originally was thinking and trying to sort out. Do you see a reason that the GenerateCLIVersions couldn't be the only place it gets changed? That would leave all the logic for everything else the same. No sure if that is the source of the problems you were having though.

**Comment by mariiatuzovska** [comment]
> ```
> 	newJSON := cliVersions{
> 		Latest: strings.TrimPrefix(releaseVersion, "v"),
> ```
> 
> So that's what I originally was thinking and trying to sort out. Do you see a reason that the GenerateCLIVersions couldn't be the only place it gets changed? That would leave all the logic for everything else the same. No sure if that is the source of the problems you were having though.

Ok, I will fix there

**Comment by sheldonhull** [comment]
@mariiatuzovska  thank you for doing this and all your contributions. Wish you the best. 👋

**Review by sheldonhull — APPROVED** [review]

**Pull request merged**
